# Robot Params
gravity: 9.806

# Init 
x_offset_init_front: 0.256266
x_offset_init_back: 0.223533
y_offset_init: 0.169227
LF_init_ori: [1.567142, -0.936286, -1.566259]
RF_init_ori: [-1.567330, -0.923703, 1.566451]
LB_init_ori: [1.566748, -0.989234, -1.565951]
RB_init_ori: [-1.566746, -0.989686, 1.565951]

# Stand
com_height: 0.6 # 0.8
com_x_offset: 0.05416
com_y_offset: -0.0155
x_offset_stand_front: 0.256266
x_offset_stand_back: 0.223533
y_offset_stand: 0.169227
LF_stand_ori: [0.146151, -0.651037, -0.088970]
RF_stand_ori: [-0.143574, -0.650245, 0.087297]
LB_stand_ori: [0.146151, -0.651037, -0.088970]
RB_stand_ori: [-0.151988, -0.649439, 0.092364]


# Homing
homing_time: 5
stand_pose: [
    0.0, 0.67, -1.3, 
    0.0, 0.67, -1.3, 
    0.0, 0.67, -1.3, 
    0.0, 0.67, -1.3 ]

# Walk Params
swing_time: 2.0 # 4.0
switch_time: 1.0 # 2.0
foot_layout: {x: 0.1, y: 0.1, x1: 0.1, y1: 0.1} #TODO to be altered
ground_clearness: 0.25 # 0.15 # 0.35 is also ok
com_x_correction: 0.020
visualize_feet_traj: True

optimizer:
  knot_period: 0.1
  knot_number: 100
  smooth_weight: 0.001
  zmp_weight: 1

# Control Params
control_frequency: 200

# Task Params
boudn_task:
  times: [1.5, 1.0, 1.5, 0.2, 0.2, 1.0, 1.5, 1.0]
  front_stretch_length: 
  front_retract_length:


# Kicking
Kicking_task:
  foot_vel: 2.0
  # com_stable: [-0.159933, -0.112818, 0.8] # l1/3, l2/3, h
  com_stable: [-0.25, -0.2, 0.45] # l1/4, l2/3, h