# Robot Params
gravity: 9.806

# Control Params
control_frequency: 1000
observation_source: state_estimator # use 'Gazebo' for model_states

# Gait
step_freq: 3.0
duty_cycle: 0.5
default_velocity_target: [0., 0., 0.]
  
# Specification for Unitree A1 Robot
foot_height_sensor_noise      :  0.001
foot_sensor_noise_position    :  0.001
foot_sensor_noise_velocity    :  0.1
foot_process_noise_position   :  0.002
imu_process_noise_position    :  0.02
imu_process_noise_velocity    :  0.02

absolute_hip_pos: [0.183, 0.047, 0.]
hip_link_length: 0.062
thigh_link_length: 0.209
calf_link_length: 0.195
calf_offset_y: 0.004

# HAA: Hip Aduction/Abduction
# HFE: Hip Felxsion/Extension
# KFE: Knee Felxsion/Extension
HAA_upper_limit: 0.8
HAA_lower_limit: -0.8
HFE_upper_limit: 4.0
HFE_lower_limit: -1.0
KFE_upper_limit: -0.9
KFE_lower_limit: -2.7

# Neural Network
standup_timesteps: 2000
standby_timesteps: 4000
policy_frequency: 100
reset_pose_path: /home/unitree/nn_loco_ws/nn_locomotion_unitree/config/
weight_path: /home/unitree/nn_loco_ws/weight/220715-172712-1400/
save_path: /home/unitree/nn_loco_ws/log/220715-172712-1400/

# test function
strech_only: False
action_replay: True
replay_length: 1500
action_record_file: /home/unitree/nn_loco_ws/weight/220715-172712-1400/actionSet_forward.csv
